### ISSUE TITLE
Missing full stop

### ISSUE THREAD

**Issue by Shraddha512** [SoftwareEngineeringToolDemos/ICSE-2012-BabelRef#3]
No full stop after the line
"Detection and Renaming Tool for Cross-Language Program Entities in Dynamic Web Applications"

**Comment by mhhassan** [comment]
How can a title have a full stop?

**Comment by manish211** [comment]
:open_mouth:

**Comment by manish211** [comment]
@Shraddha512  Is this issue also created by mistake?

@YashwanthAsh

**Comment by manish211** [comment]
If yes, then I will apply appropriate label for the sake of clarity.

**Comment by Shraddha512** [comment]
There are mixed reviews online as to add a full stop after the the subtitle or not.. Some people do put a full stop after a subtitle.
I just added an issue which I thought could be incorporated. It is up to your group to decide whether to incorporate it or not.

**Comment by mhhassan** [comment]
@SoftwareEngineeringToolDemos/beaufort 
I am going to reject this as its really not a issue and reject the pull request (Pull #5) too. Please request a pull request with only the fixes for Issue #1
