### ISSUE TITLE
Improper Spacing

### ISSUE THREAD

**Issue by Shraddha512** [SoftwareEngineeringToolDemos/ICSE-2012-BabelRef#4]
"This repository was constructed by Mohammed H Hassan under the supervision of Emerson Murphy-Hill. Thanks to Hung Viet Nguyen for his help in establishing this repository."

Space should be before the full stop and not after the full stop.

**Comment by mhhassan** [comment]
Did you put this in by mistake?

**Comment by YashwanthAsh** [comment]
Are they creating issues for these? The rule is space after fullstop not
before. We have to complain to professor about these

On Sunday, October 18, 2015, Mohammed Hasibul Hassan <
notifications@github.com> wrote:

> Did you put this in by mistake?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/issues/4#issuecomment-149094940>
> .
>


-- 
Best Regards,
Yashwanth Nallabothu
Computer Science Graduate Student
Department of Computer Science
North Carolina State University
Phone: +1-919-931-3950
Email: n.yashwanthash@gmail.com

**Comment by manish211** [comment]
You can tag the professor here . The convention here is @GithubID

**Comment by manish211** [comment]
@mhhassan @YashwanthAsh

**Comment by Shraddha512** [comment]
I put it by mistake. I think you'll can see the issue is closed.

**Comment by manish211** [comment]
unless you specify that this was a mistake, nobody can assume it was a mistake even though the issue was closed. If it was indeed a mistake, you should remove the label related to the issue otherwise it is misleading.

**Comment by manish211** [comment]
created a new label "issue-created-by-mistake" to make things clear.
