### ISSUE TITLE
including only Official Project page as hyper link

### ISSUE THREAD

**Issue by Shraddha512** [SoftwareEngineeringToolDemos/ICSE-2012-BabelRef#6]
"The Official Project Page, not including source code"
Removing not including source code part from the link

**Comment by mhhassan** [comment]
This is not really an issue.

**Comment by Shraddha512** [comment]
@CaptainEmerson  is this counted as an improvement in the README?

Right now the whole statement "The Official Project Page, not including source code" is hyper linked.
I thought it would be better if only  "The Official Project Page" is under the link.

So something like:
[The Official Project Page](http://home.engineering.iastate.edu/~hungnv/Research/BabelRef/), does not include source code

**Comment by mhhassan** [comment]
@Shraddha512, removing writing-mechanics tag as this is not an issue and only a suggested enhancement.
What you suggested with the link is different from the original template provided in the [example-repo](https://github.com/SoftwareEngineeringToolDemos/example-repo). I guess to keep it consistent with other repos, we need to follow that unless the professor suggests the change.
Leaving this open for now.

**Comment by manish211** [comment]
@mhhassan If you are following the readme template from the example-repo, there is no point of further discussion. Please close this issue.

**Comment by mhhassan** [comment]
Closing issue as this is consistent with other repos
