### ISSUE TITLE
Making it more specific and stating it as authors website

### ISSUE THREAD

**Issue by Shraddha512** [SoftwareEngineeringToolDemos/ICSE-2012-BabelRef#7]
This could be written as 
Author's personal website: http://home.engineering.iastate.edu/~hungnv/Personal/index.php
instead of
Personal website: http://home.engineering.iastate.edu/~hungnv/Personal/index.php

**Comment by mhhassan** [comment]
@Shraddha512, removing the writing-mechanics tag as this is enhancement only. Please make the change, commit and create a pull request.

**Comment by Shraddha512** [comment]
Made the changes and sent a request
