### ISSUE TITLE
Can remove the repetitive explaination

### ISSUE THREAD

**Issue by Shraddha512** [SoftwareEngineeringToolDemos/ICSE-2012-BabelRef#8]
Source: 5 (five) Eclipse projects for this tool.
Binaries: A collection of JAR files usable as is for use in an Eclipse installation

The description for these tools have been written in the latter part of the README. Could be avoided here

**Comment by mhhassan** [comment]
@Shraddha512, do you suggest leaving just bullet points and removing the summary?
Also, I removed the writing-mechanics tag as this is just enhancement and not an issue.

**Comment by Shraddha512** [comment]
Yes the summary part. Since we are waiting for the issue #6 I will clear this and the remaining two issues. I will assign you for the issue#6. You can change it depending on what the professor replies.

Does that sound good?

**Comment by mhhassan** [comment]
Yup, sounds good!

**Comment by Shraddha512** [comment]
Made the changes and sent the request.
